socket: 'tcp://127.0.0.1:8282'
timeout: 500
actions:
    leftClick:
        type: 'mouse'
        action: 'click'
        target: 'left'
        amount: 'one'
    leftDoubleClick:
        type: 'mouse'
        action: 'click'
        target: 'left'
        amount: 'two'
    mouse1Down:
        type: 'mouse'
        action: 'hold'
        target: 'left'
    mouse1Up:
        type: 'mouse'
        action: 'release'
        target: 'left'
    mouse2Down:
        type: 'mouse'
        action: 'hold'
        target: 'right'
    mouse2Up:
        type: 'mouse'
        action: 'release'
        target: 'right'
    mouseMove:
        type: 'mouse'
        action: 'move'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.7
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.7
    freeHand:
        grab:
            max: 0.4
recipes:
    mouseClick:
        action: 'leftClick'
        sign: 'pinchIndex'
    mouseClick:
        action: 'leftDoubleClick'
        sign: 'pinchRing'
    mouseMove:
        action: 'mouseMove'
        sign: 'freeHand'
