socket: 'tcp://127.0.0.1:8282'
timeout: 2000
actions:
    mouse1Down:
        type: 'mouse'
        action: 'down'
        target: 'left'
        feedback:
            audio: 'asset/audio/mousedown.ogg'
            visual:
                id: 'left'
                msg: 'Down!'
    mouse1Up:
        type: 'mouse'
        action: 'up'
        target: 'left'
        feedback:
            audio: 'asset/audio/mouseup.ogg'
            visual:
                id: 'left'
                msg: 'Up!'
    mouse2Down:
        type: 'mouse'
        action: 'down'
        target: 'right'
        feedback:
            visual:
                id: 'right'
                msg: 'Down!'
    mouse2Up:
        type: 'mouse'
        action: 'up'
        target: 'right'
        feedback:
            visual:
                id: 'right'
                msg: 'Up!'
    mouse2Click:
        type: 'mouse'
        action: 'click'
        target: 'right'
        feedback:
            audio: 'asset/audio/mallet.ogg'
    mouseScrollUp:
        type: 'mouse'
        action: 'scroll'
        direction: 'up'
        magnitude: 50
    mouseScrollDown:
        type: 'mouse'
        action: 'scroll'
        direction: 'down'
        magnitude: 50
    keyboardButtonADown:
        type: 'keyboard'
        action: 'down'
        button: 'a'
    keyboardButtonAUp:
        type: 'keyboard'
        action: 'up'
        button: 'a'
    mouseMove:
        type: 'mouse'
        action: 'move'
    mouseDelay:
        type: 'mouse'
        action: 'delay'
        delay: 100
    toggleFreeze:
        type: 'mouse'
        action: 'toggleFreeze'
        feedback:
            audio: 'asset/audio/mallet.ogg'
    keyboardButtonA:
        type: 'keyboard'
        action: 'tap'
        button: 'a'
    keyboardButtonB:
        type: 'keyboard'
        action: 'tap'
        button: 'b'
    keyboardButtonC:
        type: 'keyboard'
        action: 'tap'
        button: 'c'
    compoundActionTest:
        type: 'compound'
        actions:
         - 'keyboardButtonA'
         - 'keyboardButtonB'
         - 'keyboardButtonC'
        feedback:
            audio: 'asset/audio/mallet.ogg'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.5
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.5
    freeHand:
        grab:
            max: 0.4
    #twoCirclesDown:
    #    circle:
    #        minCircles: 2
    #        clockwise: true
    #twoCirclesUp:
    #    circle:
    #        minCircles: 2
    #        clockwise: false
    swipeDown:
        swipe:
            direction: 'down'
            minDistance: 10000
    swipeUp:
        swipe:
            direction: 'up'
            minDistance: 10000
    #stopSign:
    #    hover:
    #        left: true
    #        minDistance:
    #startSign:
    #    hover:
    #        left: false
    #        minTime: 3
    # peaceHeld:
    #     extendedFingers:
    #         indexFinger: true
    #         middleFinger: true
    #         ringFinger: false
    #         pinky: false
    #     minTime: 2000000
    #     feedback:
    #         audio: 'asset/audio/mallet.ogg'
    # surpriseHand:
    #     grab:
    #         max: 0.4
    #     feedback:
    #         audio: 'asset/audio/mallet.ogg'

recipes:
    mouseMove:
        action: 'mouseMove'
        signs:
         - 'freeHand'
        continuous: true
    mouseButton1:
        signs:
         - 'pinchIndex'
        action: 'mouse1Down'
        tearDown: 'mouse1Up'
    mouseButton2:
        signs:
         - 'pinchRing'
        action: 'mouse2Click'
        continuous: true
        chargeDelay: 500
        # compoundRecipe:
        #     signs:
        #      - 'pinchRing'
        #     action: 'compoundActionTest'
        # mouseButton1:
        #     signs:
        #      - 'pinchIndex'
        #     action: 'toggleFreeze'
        # keyboardButtonAHold:
        #     signs:
        #      - 'pinchIndex'
        #     action: 'keyboardButtonADown'
        #     tearDown: 'keyboardButtonAUp'
        #         mouseScrollDown:
        signs:
        - 'swipeDown'
        action: 'mouseScrollDown'
        #tearDown: 'startSign'
    mouseScrollUp:
        signs:
        - 'swipeUp'
        action: 'mouseScrollUp'
        #tearDown: 'startSign'
        #stop:
        #    signs:
        #    - 'stopSign'
        #    action: 'toggleFreeze'
        #start:
        #    signs:
        #    - 'startSign'
        #    action: 'toggleFreeze'
