socket: 'tcp://127.0.0.1:8282'
timeout: 500
actions:
    leftClick:
        type: 'mouse'
        action: 'hold'
        tearDown: 'release'
        target: 'left'
    rightClick:
        type: 'mouse'
        action: 'hold'
        tearDown: 'release'
        target: 'right'
    mouseMove:
        type: 'mouse'
        action: 'move'
    holdMouse:
        type: 'mouse'
        action: 'hold'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.5
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.5
    freeHand:
        grab:
            max: 0.5
    # grab:
    #     grab:
    #         min: 0.5
    #     duration:
    #         min: 200
recipes:
    leftClick:
        sign: 'pinchIndex'
    rightClick:
        sign: 'pinchRing'
    mouseGrab:
        sign: 'grab'
        action: 'holdMouse'
    mouseMove:
        action: 'mouseMove'
        sign: 'freeHand'