socket: 'tcp://127.0.0.1:8282'
timeout: 2000
actions:
    mouse1Down:
        type: 'mouse'
        action: 'hold'
        target: 'left'
        feedback:
            audio: 'asset/audio/mousedown.ogg'
    mouse1Up:
        type: 'mouse'
        action: 'release'
        target: 'left'
        feedback:
            audio: 'asset/audio/mouseup.ogg'
    mouse2Down:
        type: 'mouse'
        action: 'hold'
        target: 'right'
        feedback:
            audio: 'asset/audio/mousedown.ogg'
    mouse2Up:
        type: 'mouse'
        action: 'release'
        target: 'right'
        feedback:
            audio: 'asset/audio/mouseup.ogg'
    mouseMove:
        type: 'mouse'
        action: 'move'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.5
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.5
    freeHand:
        grab:
            max: 0.4
    peaceMan:
        grab:
            max: 0.1
        extendedFingers:
            indexFinger: 0
            middleFinger: 1
            ringFinger: 0
            pinky: 0
        feedback:
            audio: 'asset/audio/mallet.ogg'
recipes:
    mouseMove:
        action: 'mouseMove'
        signs:
         - 'freeHand'
        continuous: true
    mouseButton1:
        signs:
         - 'pinchIndex'
        action: 'mouse1Down'
        tearDown: 'mouse1Up'
        #tearDownDelay: 2000
    mouseButton2:
        signs:
         - 'pinchRing'
        action: 'mouse2Down'
        tearDown: 'mouse2Up'
