socket: 'tcp://127.0.0.1:8282'
interval: 50
stabilize: true
timeout: 2000
defaultMouseState: 'frozen'
actions:
    mouseMove:
        type: 'mouse'
        action: 'move'
    toggleFreeze:
        type: 'mouse'
        action: 'toggleFreeze'
        feedback:
            audio: 'asset/audio/message.ogg'

    mouse1Down:
        type: 'mouse'
        action: 'down'
        target: 'left'
        feedback:
            audio: 'asset/audio/button-toggle-on.ogg'
            visual:
                id: 'left'
                msg: 'Down!'
    mouse1Up:
        type: 'mouse'
        action: 'up'
        target: 'left'
        feedback:
            audio: 'asset/audio/button-toggle-off.ogg'
            visual:
                id: 'left'
                msg: 'Up!'
    mouse2Click:
        type: 'mouse'
        action: 'click'
        target: 'right'
        feedback:
            audio: 'asset/audio/button-pressed.ogg'
    mouseScrollUp:
        type: 'mouse'
        action: 'scroll'
        direction: 'up'
        magnitude: 1
        feedback:
            audio: 'asset/audio/window-slide.ogg'
    mouseScrollDown:
        type: 'mouse'
        action: 'scroll'
        direction: 'down'
        magnitude: 1
        feedback:
           audio: 'asset/audio/window-slide.ogg'
    handFound:
        type: 'filler'
        feedback:
           audio: 'asset/audio/message-new-instant.ogg'
    handLost:
        type: 'filler'
        feedback:
            audio: 'asset/audio/dialog-error.ogg'
    freezeMouse:
        type: 'mouse'
        action: 'freeze'
    handLostFreeze:
        type: 'compound'
        actions:
        - 'handLost'
        - 'freezeMouse'

signs:
    handVisible:
        grab:
            max: 1
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.9
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.9
    circleForward:
        circle:
            direction: 'forward'
            duration:
                min: 100000
    circleBackward:
        circle:
            direction: 'backward'
            duration:
                min: 100000
    grab:
        grab:
            min: 0.8
recipes:
    mouseMove:
        action: 'mouseMove'
        signs:
         - 'handVisible'
        continuous: true
    toggleFreeze:
        action: 'toggleFreeze'
        signs:
         - 'grab'
        minTime: 500000
    mouseButton1:
        signs:
         - 'pinchIndex'
        action: 'mouse1Down'
        tearDown: 'mouse1Up'
    mouseButton2:
        signs:
         - 'pinchRing'
        action: 'mouse2Click'
        continuous: false
        chargeDelay: 500
    mouseScrollDown:
        signs:
         - 'circleForward'
        action: 'mouseScrollDown'
        continuous: true
        chargeDelay: 150
    mouseScrollUp:
        signs:
         - 'circleBackward'
        action: 'mouseScrollUp'
        continuous: true
        chargeDelay: 150
    handFound:
        signs:
        - 'handVisible'
        action: 'handFound'
        tearDown: 'handLostFreeze'

